version: '3'

services:  
  mongodb:
    ports:
      - 127.0.0.1:27017:27017

  mongo_express:
    image: mongo-express:latest
    environment:
      - ME_CONFIG_OPTIONS_EDITORTHEME=default
      - ME_CONFIG_MONGODB_SERVER=mongo_db
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
      - ME_CONFIG_MONGODB_ADMINUSERNAME=${MONGO_USER}
      - ME_CONFIG_MONGODB_ADMINPASSWORD=${MONGO_PASS}
    ports:
      - 127.0.0.1:8081:8081
    restart: on-failure
    depends_on:
      - mongodb
