version: '3'

services:  
  mongodb:
    image: mongo:latest
    container_name: mongo_db
    environment:
      - TZ
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASS}
    volumes:
      - ./osteppy_data:/data/db:z
    restart: always
