version: '3'

services:
  osteppy:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - TZ
      - MONGO_USER
      - MONGO_PASS
      - PORT
      - MONGO_HOST
      - SLACK_SIGNING_SECRET
      - SLACK_BOT_USER_TOKEN
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - mongodb
    restart: always
